/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pck_proyecto;

/**
 *
 * @author User
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import pck_guis.Frm_menuPrincipal;


public class test_bd extends javax.swing.JFrame {

    /**
     * Creates new form test_bd
     */
    public test_bd() {
        initComponents();
        this.setLocationRelativeTo(null);
 
    }
    
    public void display_productos(){
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            };
            model.addColumn("ID de producto");
            model.addColumn("Nombre");
            model.addColumn("Sabor");
            model.addColumn("Precio");
        
            Tabla_datos_productos.setModel(model);
            ArrayList <Producto> datos = Producto.Consultar_tablaProductos();
            for(int i=0;i<datos.size();i++){
                String[] obj_dat = new String[4];
                obj_dat[0] = Integer.toString(datos.get(i).getIdProducto());
                obj_dat[1] = datos.get(i).getNombre();
                obj_dat[2] = datos.get(i).getSabor();
                obj_dat[3] = Float.toString(datos.get(i).getPrecio());
                model.addRow(obj_dat);
            }
    }
    int id_producto;
    String nombre;
    String sabor;
    float precio;
    int flaj_tabla=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        Txf_nombre = new javax.swing.JTextField();
        Txf_sabor = new javax.swing.JTextField();
        Txf_precio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_datos_productos = new javax.swing.JTable();
        btn_consultar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_avisos = new javax.swing.JTextArea();
        lb_consult = new javax.swing.JLabel();
        Txf_Id_busqueda = new javax.swing.JTextField();
        lb_resultado = new javax.swing.JLabel();
        btn_consul_id = new javax.swing.JToggleButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Txf_nombre_busqueda = new javax.swing.JTextField();
        btn_consultar2 = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Txf_nombre.setForeground(new java.awt.Color(153, 153, 153));
        Txf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txf_nombreActionPerformed(evt);
            }
        });

        Txf_sabor.setForeground(new java.awt.Color(153, 153, 153));
        Txf_sabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txf_saborActionPerformed(evt);
            }
        });

        Txf_precio.setForeground(new java.awt.Color(153, 153, 153));
        Txf_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txf_precioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        jLabel3.setText("Sabor:");

        jLabel4.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        jLabel4.setText("Precio:");

        btn_guardar.setText("Guardar\n");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        Tabla_datos_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla_datos_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_datos_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_datos_productos);

        btn_consultar.setText("Consultar base de datos");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_borrar.setText("Borrar producto");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        ta_avisos.setColumns(20);
        ta_avisos.setRows(5);
        jScrollPane2.setViewportView(ta_avisos);

        lb_consult.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        lb_consult.setText("Consulta por ID: ");

        btn_consul_id.setText("Consultar");
        btn_consul_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consul_idActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar operacion");
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        jLabel1.setText("Consulta por nombre:");

        btn_consultar2.setText("Consultar");
        btn_consultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar2ActionPerformed(evt);
            }
        });

        btn_atras.setBackground(new java.awt.Color(255, 0, 0));
        btn_atras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_atras.setForeground(new java.awt.Color(255, 255, 255));
        btn_atras.setText("Atrás");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_consult)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txf_Id_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_consultar2)
                                    .addComponent(btn_consul_id))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelar)
                        .addGap(41, 41, 41)
                        .addComponent(btn_atras)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Txf_nombre_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txf_sabor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_borrar)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txf_sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Txf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_borrar)
                            .addComponent(btn_consultar)
                            .addComponent(btn_modificar))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lb_consult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txf_Id_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consul_id)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancelar)
                            .addComponent(btn_atras))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txf_nombre_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultar2))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txf_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txf_precioActionPerformed
       
    }//GEN-LAST:event_Txf_precioActionPerformed

    private void Txf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txf_nombreActionPerformed
        
    }//GEN-LAST:event_Txf_nombreActionPerformed

    private void Txf_saborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txf_saborActionPerformed
        
    }//GEN-LAST:event_Txf_saborActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        display_productos();
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        id_producto = 0;
        nombre = Txf_nombre.getText();
        sabor = Txf_sabor.getText();
        precio = Float.parseFloat(Txf_precio.getText());
        Producto product = new Producto(id_producto,nombre,sabor,precio);
        product.insertar_Producto();
        display_productos();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
            flaj_tabla=1;
            ta_avisos.setText("de doble click sobre el producto a modificar");
            btn_cancelar.setEnabled(true);
            display_productos();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void Tabla_datos_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_datos_productosMouseClicked
        boolean valid;
        if(flaj_tabla == 1){
            if(evt.getClickCount() == 2){
                int filaSelec = Tabla_datos_productos.rowAtPoint(evt.getPoint());
                id_producto = Integer.parseInt(Tabla_datos_productos.getValueAt(filaSelec,0).toString());
                nombre = JOptionPane.showInputDialog("Ingrese el nombre para el producto con ID: " + id_producto);
                sabor = JOptionPane.showInputDialog("Ingrese el sabor para el producto");
                precio = Float.parseFloat(JOptionPane.showInputDialog("ingrese el precio para el producto"));
                Producto produc = new Producto();
                valid = produc.modificar_registro(id_producto, nombre, sabor, precio);
                if(valid == false){
                    JOptionPane.showMessageDialog(null,"Se realizaron los cambios con exito","Todo bien",-1);
                    ta_avisos.setText(" ");
                    flaj_tabla = 0;
                    display_productos();
                }else{
                    JOptionPane.showMessageDialog(null,"No se pudieron realizar los cambios","Error",0);
                }
            }
        }
        
        if(flaj_tabla == 2){
            if(evt.getClickCount() == 2){
                int filaSelec = Tabla_datos_productos.rowAtPoint(evt.getPoint());
                id_producto = Integer.parseInt(Tabla_datos_productos.getValueAt(filaSelec,0).toString());
                Producto produc = new Producto();
                int option = JOptionPane.showConfirmDialog(null,"Esta seguro de eliminar el dato en el ID: " + id_producto);
                if(option == 0){
                valid = produc.eliminar_dato(id_producto);
                if(valid == false){
                    JOptionPane.showMessageDialog(null,"Se borro el dato con exito","Todo bien",-1);
                    ta_avisos.setText(" ");
                    flaj_tabla = 0;
                    display_productos();
                    
                }else{
                    JOptionPane.showMessageDialog(null,"No se pudieron realizar los cambios","Error",0);
                }
                }else{
                        JOptionPane.showMessageDialog(null,"Operacion cancelada","Atencion",1);
                }
            }
        }
    }//GEN-LAST:event_Tabla_datos_productosMouseClicked

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        flaj_tabla=2;
        ta_avisos.setText("de doble click sobre el producto a borrar");
        btn_cancelar.setEnabled(true);
        display_productos();
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_consul_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consul_idActionPerformed
        int id = Integer.parseInt(Txf_Id_busqueda.getText());
        Producto prod = new Producto();
        prod.busqueda_id(id);
    }//GEN-LAST:event_btn_consul_idActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        flaj_tabla = 0;
        JOptionPane.showMessageDialog(null,"Operacion cancelada","atencion",-1);
        ta_avisos.setText("");
        btn_cancelar.setEnabled(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_consultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar2ActionPerformed
        String nombre = Txf_nombre_busqueda.getText();
        Producto prod = new Producto();
        prod.busqueda_nombre(nombre);
    }//GEN-LAST:event_btn_consultar2ActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        Frm_menuPrincipal ventana = new Frm_menuPrincipal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test_bd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test_bd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test_bd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test_bd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test_bd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_datos_productos;
    private javax.swing.JTextField Txf_Id_busqueda;
    private javax.swing.JTextField Txf_nombre;
    private javax.swing.JTextField Txf_nombre_busqueda;
    private javax.swing.JTextField Txf_precio;
    private javax.swing.JTextField Txf_sabor;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JToggleButton btn_consul_id;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_consultar2;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_consult;
    private javax.swing.JLabel lb_resultado;
    private javax.swing.JTextArea ta_avisos;
    // End of variables declaration//GEN-END:variables
}
