package pck_guis;

import pck_proyecto.test_bd;

public class Frm_gestionUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Frm_menuPrincipal
     */
    public Frm_gestionUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_rol = new javax.swing.JLabel();
        btn_fotoPerfil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();
        btn_ventaHelado = new javax.swing.JButton();
        btn_inventario = new javax.swing.JButton();
        btn_regVentas = new javax.swing.JButton();
        btn_horarios = new javax.swing.JButton();
        btn_gestionUsuarios = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_agregarUsuario = new javax.swing.JButton();
        btn_modificarUsuario = new javax.swing.JButton();
        btn_eliminarUsuario = new javax.swing.JButton();
        btn__icon_agregarUsuario = new javax.swing.JButton();
        btn_icon_modificarUsuario = new javax.swing.JButton();
        btn_icon_eliminarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(196, 196, 196));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(98, 121, 147));

        lbl_nombre.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("[Nombre(s) Apellido(s)]");

        lbl_rol.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_rol.setForeground(new java.awt.Color(244, 165, 86));
        lbl_rol.setText("[Empleado/Administrador]");

        btn_fotoPerfil.setText("Foto");
        btn_fotoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fotoPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(btn_fotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_rol, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_fotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_rol)
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(97, 101, 146));

        jPanel1.setBackground(new java.awt.Color(52, 61, 120));

        btn_menu.setBackground(new java.awt.Color(52, 61, 120));
        btn_menu.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/Icon_home.png"))); // NOI18N
        btn_menu.setText("Menú");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btn_ventaHelado.setBackground(new java.awt.Color(97, 101, 146));
        btn_ventaHelado.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btn_ventaHelado.setForeground(new java.awt.Color(255, 255, 255));
        btn_ventaHelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icon_agregar.png"))); // NOI18N
        btn_ventaHelado.setText("Venta de helado");
        btn_ventaHelado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_inventario.setBackground(new java.awt.Color(97, 101, 146));
        btn_inventario.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btn_inventario.setForeground(new java.awt.Color(255, 255, 255));
        btn_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icon_caja.png"))); // NOI18N
        btn_inventario.setText("Inventario");
        btn_inventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });

        btn_regVentas.setBackground(new java.awt.Color(97, 101, 146));
        btn_regVentas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btn_regVentas.setForeground(new java.awt.Color(255, 255, 255));
        btn_regVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icon_registroVentas.png"))); // NOI18N
        btn_regVentas.setText("Registro de ventas");
        btn_regVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_horarios.setBackground(new java.awt.Color(97, 101, 146));
        btn_horarios.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btn_horarios.setForeground(new java.awt.Color(255, 255, 255));
        btn_horarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icon_reloj.png"))); // NOI18N
        btn_horarios.setText("Horarios");
        btn_horarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_gestionUsuarios.setBackground(new java.awt.Color(97, 101, 146));
        btn_gestionUsuarios.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btn_gestionUsuarios.setForeground(new java.awt.Color(80, 195, 244));
        btn_gestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icon_gestionar.png"))); // NOI18N
        btn_gestionUsuarios.setText("Gestión de usuarios");
        btn_gestionUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_salir.setBackground(new java.awt.Color(97, 101, 146));
        btn_salir.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icon_salirMenu.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ventaHelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_regVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_horarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_gestionUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_ventaHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_regVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_gestionUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salir)
                .addGap(25, 25, 25))
        );

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLabel2.setText("Gestión de usuarios");

        btn_agregarUsuario.setBackground(new java.awt.Color(204, 255, 204));
        btn_agregarUsuario.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        btn_agregarUsuario.setForeground(new java.awt.Color(0, 204, 0));
        btn_agregarUsuario.setText("Alta de usuario");
        btn_agregarUsuario.setBorder(null);
        btn_agregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarUsuarioActionPerformed(evt);
            }
        });

        btn_modificarUsuario.setBackground(new java.awt.Color(255, 255, 204));
        btn_modificarUsuario.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        btn_modificarUsuario.setForeground(new java.awt.Color(204, 204, 0));
        btn_modificarUsuario.setText("Modificar usuario");
        btn_modificarUsuario.setBorder(null);
        btn_modificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarUsuarioActionPerformed(evt);
            }
        });

        btn_eliminarUsuario.setBackground(new java.awt.Color(255, 204, 204));
        btn_eliminarUsuario.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        btn_eliminarUsuario.setForeground(new java.awt.Color(255, 0, 0));
        btn_eliminarUsuario.setText("Eliminar usuario");
        btn_eliminarUsuario.setBorder(null);
        btn_eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarUsuarioActionPerformed(evt);
            }
        });

        btn__icon_agregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icon_agregarUsuario.png"))); // NOI18N
        btn__icon_agregarUsuario.setContentAreaFilled(false);
        btn__icon_agregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__icon_agregarUsuarioActionPerformed(evt);
            }
        });

        btn_icon_modificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icono_modificarUsuario.png"))); // NOI18N
        btn_icon_modificarUsuario.setContentAreaFilled(false);
        btn_icon_modificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icon_modificarUsuarioActionPerformed(evt);
            }
        });

        btn_icon_eliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck_icons/icono_eliminarUsuario.png"))); // NOI18N
        btn_icon_eliminarUsuario.setContentAreaFilled(false);
        btn_icon_eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icon_eliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(183, 183, 183))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_icon_modificarUsuario)
                            .addComponent(btn__icon_agregarUsuario)
                            .addComponent(btn_icon_eliminarUsuario))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_modificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_agregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn__icon_agregarUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_agregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_modificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btn_eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_icon_modificarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btn_icon_eliminarUsuario)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarUsuarioActionPerformed
        Frm_altaUsuario ventana = new Frm_altaUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregarUsuarioActionPerformed

    private void btn_modificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarUsuarioActionPerformed
        frm_ModificarUsuario ventana = new frm_ModificarUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_modificarUsuarioActionPerformed

    private void btn_eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioActionPerformed
        frm_EliminarUsuario ventana = new frm_EliminarUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_eliminarUsuarioActionPerformed

    private void btn__icon_agregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__icon_agregarUsuarioActionPerformed
        Frm_altaUsuario ventana = new Frm_altaUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn__icon_agregarUsuarioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
            this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_icon_modificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icon_modificarUsuarioActionPerformed
        frm_ModificarUsuario ventana = new frm_ModificarUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_icon_modificarUsuarioActionPerformed

    private void btn_icon_eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icon_eliminarUsuarioActionPerformed
        frm_EliminarUsuario ventana = new frm_EliminarUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_icon_eliminarUsuarioActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        test_bd ventana = new test_bd();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_fotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fotoPerfilActionPerformed
        Frm_login ventana = new Frm_login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_fotoPerfilActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        Frm_menuPrincipal ventana = new Frm_menuPrincipal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_gestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn__icon_agregarUsuario;
    private javax.swing.JButton btn_agregarUsuario;
    private javax.swing.JButton btn_eliminarUsuario;
    private javax.swing.JButton btn_fotoPerfil;
    private javax.swing.JButton btn_gestionUsuarios;
    private javax.swing.JButton btn_horarios;
    private javax.swing.JButton btn_icon_eliminarUsuario;
    private javax.swing.JButton btn_icon_modificarUsuario;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_modificarUsuario;
    private javax.swing.JButton btn_regVentas;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_ventaHelado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_rol;
    // End of variables declaration//GEN-END:variables
}
